### ISSUE TITLE
Enhancement: What are your plans? I have a suggestion

### ISSUE THREAD

**Issue by pjlasl** [AppleRoar/CoinsMod#1]
It would be great to implement this into the trading aspect of the game with villagers or wandering traders.

**Comment by AppleRoar** [comment]
> It would be great to implement this into the trading aspect of the game with villagers or wandering traders.

Thank you for the suggestion.  I am currently implementing that feature.

**Comment by AppleRoar** [comment]
I have now implemented villager trading with coins.
